### PR TITLE
Issue/quick 124 get high xl apdex

### PR DESCRIPTION
**Pull request by dagguh**

### CODE REVIEW

**Comment by dagguh** [comment]
Spinning: https://server-gdn-bamboo.internal.atlassian.com/browse/QUICK-JHWR23-4

**Review by kema2000 — APPROVED** [review]

**Comment by dagguh** [comment]
The build failed:
```
 #64: TESTED: 0, SKIPPED: 52, FAILED: 12, REMAINING: 0
```

11/12 failures are about failing to install an Ubuntu package, e.g.:
```
Failed to install [zip, python] despite 2 attempts
```

`Ubuntu.install` was known to be flaky.
https://ecosystem.atlassian.net/browse/JPERF-219
https://ecosystem.atlassian.net/browse/JPERF-387
I'm going to investigate.

**Comment by dagguh** [comment]
```
grep "Stacktrace for" detailed.log -A1 | grep -v "Stacktrace for" | grep -v "\-\-" | sort | uniq -c | sort -nr
 270 java.lang.IllegalStateException: Not connected
  51 net.schmizz.sshj.connection.ConnectionException: Timeout expired
   7 net.schmizz.sshj.connection.ConnectionException: Connection timed out (Read failed)
   1 java.lang.Exception: SSH command failed to finish in extended time (PT6M15S): SshExecutedCommand(cmd=sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq unzip libx11-xcb1 libxcomposite1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpango1.0 libatk1.0-0 libatk-bridge2.0 libgtk-3-0, stdout=<couldn't get command stdout>, stderr=<couldn't get command stderr>)
   1 java.lang.Exception: SSH command failed to finish in extended time (PT6M15S): SshExecutedCommand(cmd=sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq openjdk-8-jdk, stdout=<couldn't get command stdout>, stderr=<couldn't get command stderr>)
```

**Comment by dagguh** [comment]
```
2019-05-06T15:34:14,680Z DEBUG <multicast-virtual-users-provisioning-thread-0> {cohort=3 x c5.18xlarge Jira, m4.4xlarge DB, run 1} [3 x c5.18xlarge Jira, m4.4xlarge DB, run
 1, virtual users, provision virtual users 1] [com.atlassian.performance.tools.aws.api.StackFormula] Stack jpt-7e96f3c3-ed37-440c-ad07-cbc10688bd2a1-59e21ec2 is operational
: CREATE_COMPLETE
...
2019-05-06T15:51:05,044Z DEBUG <multicast-virtual-users-provisioning-thread-0> {cohort=3 x c5.18xlarge Jira, m4.4xlarge DB, run 1} [3 x c5.18xlarge Jira, m4.4xlarge DB, run 1, virtual users, provision virtual users 1] [com.atlassian.performance.tools.ssh.SshjConnection] bash: aws: command not found
...
2019-05-06T17:09:57,071Z DEBUG <multicast-virtual-users-provisioning-thread-0> {cohort=3 x c5.18xlarge Jira, m4.4xlarge DB, run 1} [3 x c5.18xlarge Jira, m4.4xlarge DB, run 1, virtual users, provision virtual users 1] [com.atlassian.performance.tools.jvmtasks.api.IdempotentAction.Companion] Attempt #1 failed to install [zip, python], Not connected, backing off for PT10S ...
```

There's a gap of over 1 hour during the installation of AWS CLI.
At 17:09, the instance was still up:
image
But the SSH connection might not have survived an hour of silence.

**Comment by dagguh** [comment]
Oh god, I found it:
```
    private companion object {
        private val lock = Object()
    }

    private fun tryInstalling(
        ssh: SshConnection,
        packages: List<String>,
        timeout: Duration
    ) {
        val joinedPackages = packages.joinToString(separator = " ")
        synchronized(lock) {
            ssh.execute("sudo rm -rf /var/lib/apt/lists/*")
            ssh.execute("sudo apt-get update -qq", Duration.ofMinutes(1))
            ssh.execute(
                cmd = "sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq $joinedPackages",
                timeout = timeout,
                stdout = Level.TRACE,
                stderr = Level.TRACE
            )
        }
    }
```
It uses a global lock for all Ubuntu installs! It is superbly awful for any parallelization.
We gotta avoid this. The fastest workaround is to revert `infrastructure` to 4.12.1.

**Comment by wyrzyk** [comment]
If you're going to revert `infrastructure` to 4.12.1 you should also revert `aws-infrastructure` to 2.7.3  to avoid JPERF-468.

**Comment by dagguh** [comment]
Thanks for the heads up. Fortunately, Gradle would detect that, because https://github.com/atlassian/aws-infrastructure/commit/7638afa9c3f08e7ac32e7c14aeff37365f4f71dd (unreleased) depends on `com.atlassian.performance.tools:infrastructure:[4.12.2,5.0.0)`.

**Comment by dagguh** [comment]
Spinning: https://server-gdn-bamboo.internal.atlassian.com/browse/QUICK-JHWR23-6

**Comment by dagguh** [comment]
We might have merged it prematurely, the [results](https://s3-eu-west-1.amazonaws.com/quicksilver-jhwr-cache-ireland/QUICK-124-cherry-picked-v2/jira-exploration-chart.html) do not show high Apdex for Jira XL.
Also: `#64: TESTED: 4, SKIPPED: 51, FAILED: 9, REMAINING: 0`

**Comment by dagguh** [comment]
Followup: https://github.com/atlassian/jira-hardware-exploration/pull/36

**Pull request merged**
